FROM node:22-alpine AS builder

WORKDIR /app
COPY . .

RUN apk update && apk add --no-cache --force-overwrite --virtual .gyp make gcc g++ libc6-compat bash python3 py3-pip
RUN npm install -g bun
RUN npm install -g node-gyp

RUN bun install --frozen-lockfile
RUN bun run build
RUN apk del .gyp

FROM nginx:1-alpine
WORKDIR /app
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
